app = "desprong"

[build]
  # Gebruik de Docker images die door je pipeline zijn gepusht
  image = "ghcr.io/<your-repo-name>:backend-latest"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]

[[services]]
  # Frontend service
  internal_port = 5173
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
