name: Deploy to Fly.io

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: "latest"
          
      - name: Deploy the app to Fly.io
        run: |
          flyctl auth token ${{ secrets.FLY_API_TOKEN }}
          flyctl apps list
          flyctl apps set-context --app desprong --org personal
          flyctl deploy --remote-only --app desprong
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
